//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductReading.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonTable
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> RefreshTime { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
