//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductReading.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommonTable> CommonTables { get; set; }
        public virtual DbSet<ProductRecord> ProductRecords { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<ProductRecord> sp_AddUpdateProductRecord(Nullable<int> statementType, Nullable<int> id, string isNew, string productImagePath, string product_SKU, string product_Group, string manufacturer, string product_Type, string product_Name, string short_Description, string long_Description, string level_1_Category, string level_2_Category, string uPC_Code, string mAP_Price, string kroll_Sell, string mSRP, string product_Weight, string small_Image_File, string small_Image_Text, string manu_Part_Number, string hazardous, string restricted, string complete_SKU, string sKU_Variation, string parent_SKU, string choice1, string option1, string choice2, string option2, string choice3, string option3, string choice4, string option4, string choice5, string option5, string choice6, string option6, string choice7, string option7, string choice8, string option8, string choice9, string option9, string choice10, string option10, string country_of_Origin_Code, Nullable<int> isActive, Nullable<System.DateTime> createdAt)
        {
            var statementTypeParameter = statementType.HasValue ?
                new ObjectParameter("StatementType", statementType) :
                new ObjectParameter("StatementType", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var isNewParameter = isNew != null ?
                new ObjectParameter("IsNew", isNew) :
                new ObjectParameter("IsNew", typeof(string));
    
            var productImagePathParameter = productImagePath != null ?
                new ObjectParameter("ProductImagePath", productImagePath) :
                new ObjectParameter("ProductImagePath", typeof(string));
    
            var product_SKUParameter = product_SKU != null ?
                new ObjectParameter("Product_SKU", product_SKU) :
                new ObjectParameter("Product_SKU", typeof(string));
    
            var product_GroupParameter = product_Group != null ?
                new ObjectParameter("Product_Group", product_Group) :
                new ObjectParameter("Product_Group", typeof(string));
    
            var manufacturerParameter = manufacturer != null ?
                new ObjectParameter("Manufacturer", manufacturer) :
                new ObjectParameter("Manufacturer", typeof(string));
    
            var product_TypeParameter = product_Type != null ?
                new ObjectParameter("Product_Type", product_Type) :
                new ObjectParameter("Product_Type", typeof(string));
    
            var product_NameParameter = product_Name != null ?
                new ObjectParameter("Product_Name", product_Name) :
                new ObjectParameter("Product_Name", typeof(string));
    
            var short_DescriptionParameter = short_Description != null ?
                new ObjectParameter("Short_Description", short_Description) :
                new ObjectParameter("Short_Description", typeof(string));
    
            var long_DescriptionParameter = long_Description != null ?
                new ObjectParameter("Long_Description", long_Description) :
                new ObjectParameter("Long_Description", typeof(string));
    
            var level_1_CategoryParameter = level_1_Category != null ?
                new ObjectParameter("Level_1_Category", level_1_Category) :
                new ObjectParameter("Level_1_Category", typeof(string));
    
            var level_2_CategoryParameter = level_2_Category != null ?
                new ObjectParameter("Level_2_Category", level_2_Category) :
                new ObjectParameter("Level_2_Category", typeof(string));
    
            var uPC_CodeParameter = uPC_Code != null ?
                new ObjectParameter("UPC_Code", uPC_Code) :
                new ObjectParameter("UPC_Code", typeof(string));
    
            var mAP_PriceParameter = mAP_Price != null ?
                new ObjectParameter("MAP_Price", mAP_Price) :
                new ObjectParameter("MAP_Price", typeof(string));
    
            var kroll_SellParameter = kroll_Sell != null ?
                new ObjectParameter("Kroll_Sell", kroll_Sell) :
                new ObjectParameter("Kroll_Sell", typeof(string));
    
            var mSRPParameter = mSRP != null ?
                new ObjectParameter("MSRP", mSRP) :
                new ObjectParameter("MSRP", typeof(string));
    
            var product_WeightParameter = product_Weight != null ?
                new ObjectParameter("Product_Weight", product_Weight) :
                new ObjectParameter("Product_Weight", typeof(string));
    
            var small_Image_FileParameter = small_Image_File != null ?
                new ObjectParameter("Small_Image_File", small_Image_File) :
                new ObjectParameter("Small_Image_File", typeof(string));
    
            var small_Image_TextParameter = small_Image_Text != null ?
                new ObjectParameter("Small_Image_Text", small_Image_Text) :
                new ObjectParameter("Small_Image_Text", typeof(string));
    
            var manu_Part_NumberParameter = manu_Part_Number != null ?
                new ObjectParameter("Manu_Part_Number", manu_Part_Number) :
                new ObjectParameter("Manu_Part_Number", typeof(string));
    
            var hazardousParameter = hazardous != null ?
                new ObjectParameter("Hazardous", hazardous) :
                new ObjectParameter("Hazardous", typeof(string));
    
            var restrictedParameter = restricted != null ?
                new ObjectParameter("Restricted", restricted) :
                new ObjectParameter("Restricted", typeof(string));
    
            var complete_SKUParameter = complete_SKU != null ?
                new ObjectParameter("Complete_SKU", complete_SKU) :
                new ObjectParameter("Complete_SKU", typeof(string));
    
            var sKU_VariationParameter = sKU_Variation != null ?
                new ObjectParameter("SKU_Variation", sKU_Variation) :
                new ObjectParameter("SKU_Variation", typeof(string));
    
            var parent_SKUParameter = parent_SKU != null ?
                new ObjectParameter("Parent_SKU", parent_SKU) :
                new ObjectParameter("Parent_SKU", typeof(string));
    
            var choice1Parameter = choice1 != null ?
                new ObjectParameter("Choice1", choice1) :
                new ObjectParameter("Choice1", typeof(string));
    
            var option1Parameter = option1 != null ?
                new ObjectParameter("Option1", option1) :
                new ObjectParameter("Option1", typeof(string));
    
            var choice2Parameter = choice2 != null ?
                new ObjectParameter("Choice2", choice2) :
                new ObjectParameter("Choice2", typeof(string));
    
            var option2Parameter = option2 != null ?
                new ObjectParameter("Option2", option2) :
                new ObjectParameter("Option2", typeof(string));
    
            var choice3Parameter = choice3 != null ?
                new ObjectParameter("Choice3", choice3) :
                new ObjectParameter("Choice3", typeof(string));
    
            var option3Parameter = option3 != null ?
                new ObjectParameter("Option3", option3) :
                new ObjectParameter("Option3", typeof(string));
    
            var choice4Parameter = choice4 != null ?
                new ObjectParameter("Choice4", choice4) :
                new ObjectParameter("Choice4", typeof(string));
    
            var option4Parameter = option4 != null ?
                new ObjectParameter("Option4", option4) :
                new ObjectParameter("Option4", typeof(string));
    
            var choice5Parameter = choice5 != null ?
                new ObjectParameter("Choice5", choice5) :
                new ObjectParameter("Choice5", typeof(string));
    
            var option5Parameter = option5 != null ?
                new ObjectParameter("Option5", option5) :
                new ObjectParameter("Option5", typeof(string));
    
            var choice6Parameter = choice6 != null ?
                new ObjectParameter("Choice6", choice6) :
                new ObjectParameter("Choice6", typeof(string));
    
            var option6Parameter = option6 != null ?
                new ObjectParameter("Option6", option6) :
                new ObjectParameter("Option6", typeof(string));
    
            var choice7Parameter = choice7 != null ?
                new ObjectParameter("Choice7", choice7) :
                new ObjectParameter("Choice7", typeof(string));
    
            var option7Parameter = option7 != null ?
                new ObjectParameter("Option7", option7) :
                new ObjectParameter("Option7", typeof(string));
    
            var choice8Parameter = choice8 != null ?
                new ObjectParameter("Choice8", choice8) :
                new ObjectParameter("Choice8", typeof(string));
    
            var option8Parameter = option8 != null ?
                new ObjectParameter("Option8", option8) :
                new ObjectParameter("Option8", typeof(string));
    
            var choice9Parameter = choice9 != null ?
                new ObjectParameter("Choice9", choice9) :
                new ObjectParameter("Choice9", typeof(string));
    
            var option9Parameter = option9 != null ?
                new ObjectParameter("Option9", option9) :
                new ObjectParameter("Option9", typeof(string));
    
            var choice10Parameter = choice10 != null ?
                new ObjectParameter("Choice10", choice10) :
                new ObjectParameter("Choice10", typeof(string));
    
            var option10Parameter = option10 != null ?
                new ObjectParameter("Option10", option10) :
                new ObjectParameter("Option10", typeof(string));
    
            var country_of_Origin_CodeParameter = country_of_Origin_Code != null ?
                new ObjectParameter("Country_of_Origin_Code", country_of_Origin_Code) :
                new ObjectParameter("Country_of_Origin_Code", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(int));
    
            var createdAtParameter = createdAt.HasValue ?
                new ObjectParameter("CreatedAt", createdAt) :
                new ObjectParameter("CreatedAt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductRecord>("sp_AddUpdateProductRecord", statementTypeParameter, idParameter, isNewParameter, productImagePathParameter, product_SKUParameter, product_GroupParameter, manufacturerParameter, product_TypeParameter, product_NameParameter, short_DescriptionParameter, long_DescriptionParameter, level_1_CategoryParameter, level_2_CategoryParameter, uPC_CodeParameter, mAP_PriceParameter, kroll_SellParameter, mSRPParameter, product_WeightParameter, small_Image_FileParameter, small_Image_TextParameter, manu_Part_NumberParameter, hazardousParameter, restrictedParameter, complete_SKUParameter, sKU_VariationParameter, parent_SKUParameter, choice1Parameter, option1Parameter, choice2Parameter, option2Parameter, choice3Parameter, option3Parameter, choice4Parameter, option4Parameter, choice5Parameter, option5Parameter, choice6Parameter, option6Parameter, choice7Parameter, option7Parameter, choice8Parameter, option8Parameter, choice9Parameter, option9Parameter, choice10Parameter, option10Parameter, country_of_Origin_CodeParameter, isActiveParameter, createdAtParameter);
        }
    
        public virtual ObjectResult<ProductRecord> sp_AddUpdateProductRecord(Nullable<int> statementType, Nullable<int> id, string isNew, string productImagePath, string product_SKU, string product_Group, string manufacturer, string product_Type, string product_Name, string short_Description, string long_Description, string level_1_Category, string level_2_Category, string uPC_Code, string mAP_Price, string kroll_Sell, string mSRP, string product_Weight, string small_Image_File, string small_Image_Text, string manu_Part_Number, string hazardous, string restricted, string complete_SKU, string sKU_Variation, string parent_SKU, string choice1, string option1, string choice2, string option2, string choice3, string option3, string choice4, string option4, string choice5, string option5, string choice6, string option6, string choice7, string option7, string choice8, string option8, string choice9, string option9, string choice10, string option10, string country_of_Origin_Code, Nullable<int> isActive, Nullable<System.DateTime> createdAt, MergeOption mergeOption)
        {
            var statementTypeParameter = statementType.HasValue ?
                new ObjectParameter("StatementType", statementType) :
                new ObjectParameter("StatementType", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var isNewParameter = isNew != null ?
                new ObjectParameter("IsNew", isNew) :
                new ObjectParameter("IsNew", typeof(string));
    
            var productImagePathParameter = productImagePath != null ?
                new ObjectParameter("ProductImagePath", productImagePath) :
                new ObjectParameter("ProductImagePath", typeof(string));
    
            var product_SKUParameter = product_SKU != null ?
                new ObjectParameter("Product_SKU", product_SKU) :
                new ObjectParameter("Product_SKU", typeof(string));
    
            var product_GroupParameter = product_Group != null ?
                new ObjectParameter("Product_Group", product_Group) :
                new ObjectParameter("Product_Group", typeof(string));
    
            var manufacturerParameter = manufacturer != null ?
                new ObjectParameter("Manufacturer", manufacturer) :
                new ObjectParameter("Manufacturer", typeof(string));
    
            var product_TypeParameter = product_Type != null ?
                new ObjectParameter("Product_Type", product_Type) :
                new ObjectParameter("Product_Type", typeof(string));
    
            var product_NameParameter = product_Name != null ?
                new ObjectParameter("Product_Name", product_Name) :
                new ObjectParameter("Product_Name", typeof(string));
    
            var short_DescriptionParameter = short_Description != null ?
                new ObjectParameter("Short_Description", short_Description) :
                new ObjectParameter("Short_Description", typeof(string));
    
            var long_DescriptionParameter = long_Description != null ?
                new ObjectParameter("Long_Description", long_Description) :
                new ObjectParameter("Long_Description", typeof(string));
    
            var level_1_CategoryParameter = level_1_Category != null ?
                new ObjectParameter("Level_1_Category", level_1_Category) :
                new ObjectParameter("Level_1_Category", typeof(string));
    
            var level_2_CategoryParameter = level_2_Category != null ?
                new ObjectParameter("Level_2_Category", level_2_Category) :
                new ObjectParameter("Level_2_Category", typeof(string));
    
            var uPC_CodeParameter = uPC_Code != null ?
                new ObjectParameter("UPC_Code", uPC_Code) :
                new ObjectParameter("UPC_Code", typeof(string));
    
            var mAP_PriceParameter = mAP_Price != null ?
                new ObjectParameter("MAP_Price", mAP_Price) :
                new ObjectParameter("MAP_Price", typeof(string));
    
            var kroll_SellParameter = kroll_Sell != null ?
                new ObjectParameter("Kroll_Sell", kroll_Sell) :
                new ObjectParameter("Kroll_Sell", typeof(string));
    
            var mSRPParameter = mSRP != null ?
                new ObjectParameter("MSRP", mSRP) :
                new ObjectParameter("MSRP", typeof(string));
    
            var product_WeightParameter = product_Weight != null ?
                new ObjectParameter("Product_Weight", product_Weight) :
                new ObjectParameter("Product_Weight", typeof(string));
    
            var small_Image_FileParameter = small_Image_File != null ?
                new ObjectParameter("Small_Image_File", small_Image_File) :
                new ObjectParameter("Small_Image_File", typeof(string));
    
            var small_Image_TextParameter = small_Image_Text != null ?
                new ObjectParameter("Small_Image_Text", small_Image_Text) :
                new ObjectParameter("Small_Image_Text", typeof(string));
    
            var manu_Part_NumberParameter = manu_Part_Number != null ?
                new ObjectParameter("Manu_Part_Number", manu_Part_Number) :
                new ObjectParameter("Manu_Part_Number", typeof(string));
    
            var hazardousParameter = hazardous != null ?
                new ObjectParameter("Hazardous", hazardous) :
                new ObjectParameter("Hazardous", typeof(string));
    
            var restrictedParameter = restricted != null ?
                new ObjectParameter("Restricted", restricted) :
                new ObjectParameter("Restricted", typeof(string));
    
            var complete_SKUParameter = complete_SKU != null ?
                new ObjectParameter("Complete_SKU", complete_SKU) :
                new ObjectParameter("Complete_SKU", typeof(string));
    
            var sKU_VariationParameter = sKU_Variation != null ?
                new ObjectParameter("SKU_Variation", sKU_Variation) :
                new ObjectParameter("SKU_Variation", typeof(string));
    
            var parent_SKUParameter = parent_SKU != null ?
                new ObjectParameter("Parent_SKU", parent_SKU) :
                new ObjectParameter("Parent_SKU", typeof(string));
    
            var choice1Parameter = choice1 != null ?
                new ObjectParameter("Choice1", choice1) :
                new ObjectParameter("Choice1", typeof(string));
    
            var option1Parameter = option1 != null ?
                new ObjectParameter("Option1", option1) :
                new ObjectParameter("Option1", typeof(string));
    
            var choice2Parameter = choice2 != null ?
                new ObjectParameter("Choice2", choice2) :
                new ObjectParameter("Choice2", typeof(string));
    
            var option2Parameter = option2 != null ?
                new ObjectParameter("Option2", option2) :
                new ObjectParameter("Option2", typeof(string));
    
            var choice3Parameter = choice3 != null ?
                new ObjectParameter("Choice3", choice3) :
                new ObjectParameter("Choice3", typeof(string));
    
            var option3Parameter = option3 != null ?
                new ObjectParameter("Option3", option3) :
                new ObjectParameter("Option3", typeof(string));
    
            var choice4Parameter = choice4 != null ?
                new ObjectParameter("Choice4", choice4) :
                new ObjectParameter("Choice4", typeof(string));
    
            var option4Parameter = option4 != null ?
                new ObjectParameter("Option4", option4) :
                new ObjectParameter("Option4", typeof(string));
    
            var choice5Parameter = choice5 != null ?
                new ObjectParameter("Choice5", choice5) :
                new ObjectParameter("Choice5", typeof(string));
    
            var option5Parameter = option5 != null ?
                new ObjectParameter("Option5", option5) :
                new ObjectParameter("Option5", typeof(string));
    
            var choice6Parameter = choice6 != null ?
                new ObjectParameter("Choice6", choice6) :
                new ObjectParameter("Choice6", typeof(string));
    
            var option6Parameter = option6 != null ?
                new ObjectParameter("Option6", option6) :
                new ObjectParameter("Option6", typeof(string));
    
            var choice7Parameter = choice7 != null ?
                new ObjectParameter("Choice7", choice7) :
                new ObjectParameter("Choice7", typeof(string));
    
            var option7Parameter = option7 != null ?
                new ObjectParameter("Option7", option7) :
                new ObjectParameter("Option7", typeof(string));
    
            var choice8Parameter = choice8 != null ?
                new ObjectParameter("Choice8", choice8) :
                new ObjectParameter("Choice8", typeof(string));
    
            var option8Parameter = option8 != null ?
                new ObjectParameter("Option8", option8) :
                new ObjectParameter("Option8", typeof(string));
    
            var choice9Parameter = choice9 != null ?
                new ObjectParameter("Choice9", choice9) :
                new ObjectParameter("Choice9", typeof(string));
    
            var option9Parameter = option9 != null ?
                new ObjectParameter("Option9", option9) :
                new ObjectParameter("Option9", typeof(string));
    
            var choice10Parameter = choice10 != null ?
                new ObjectParameter("Choice10", choice10) :
                new ObjectParameter("Choice10", typeof(string));
    
            var option10Parameter = option10 != null ?
                new ObjectParameter("Option10", option10) :
                new ObjectParameter("Option10", typeof(string));
    
            var country_of_Origin_CodeParameter = country_of_Origin_Code != null ?
                new ObjectParameter("Country_of_Origin_Code", country_of_Origin_Code) :
                new ObjectParameter("Country_of_Origin_Code", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(int));
    
            var createdAtParameter = createdAt.HasValue ?
                new ObjectParameter("CreatedAt", createdAt) :
                new ObjectParameter("CreatedAt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductRecord>("sp_AddUpdateProductRecord", mergeOption, statementTypeParameter, idParameter, isNewParameter, productImagePathParameter, product_SKUParameter, product_GroupParameter, manufacturerParameter, product_TypeParameter, product_NameParameter, short_DescriptionParameter, long_DescriptionParameter, level_1_CategoryParameter, level_2_CategoryParameter, uPC_CodeParameter, mAP_PriceParameter, kroll_SellParameter, mSRPParameter, product_WeightParameter, small_Image_FileParameter, small_Image_TextParameter, manu_Part_NumberParameter, hazardousParameter, restrictedParameter, complete_SKUParameter, sKU_VariationParameter, parent_SKUParameter, choice1Parameter, option1Parameter, choice2Parameter, option2Parameter, choice3Parameter, option3Parameter, choice4Parameter, option4Parameter, choice5Parameter, option5Parameter, choice6Parameter, option6Parameter, choice7Parameter, option7Parameter, choice8Parameter, option8Parameter, choice9Parameter, option9Parameter, choice10Parameter, option10Parameter, country_of_Origin_CodeParameter, isActiveParameter, createdAtParameter);
        }
    
        public virtual ObjectResult<ProductRecord> sp_GetActiveProductById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductRecord>("sp_GetActiveProductById", idParameter);
        }
    
        public virtual ObjectResult<ProductRecord> sp_GetActiveProductById(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductRecord>("sp_GetActiveProductById", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<ProductRecord> sp_GetActiveProductBySku(string product_SKU)
        {
            var product_SKUParameter = product_SKU != null ?
                new ObjectParameter("Product_SKU", product_SKU) :
                new ObjectParameter("Product_SKU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductRecord>("sp_GetActiveProductBySku", product_SKUParameter);
        }
    
        public virtual ObjectResult<ProductRecord> sp_GetActiveProductBySku(string product_SKU, MergeOption mergeOption)
        {
            var product_SKUParameter = product_SKU != null ?
                new ObjectParameter("Product_SKU", product_SKU) :
                new ObjectParameter("Product_SKU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductRecord>("sp_GetActiveProductBySku", mergeOption, product_SKUParameter);
        }
    
        public virtual ObjectResult<ProductRecord> sp_GetActiveProductList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductRecord>("sp_GetActiveProductList");
        }
    
        public virtual ObjectResult<ProductRecord> sp_GetActiveProductList(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductRecord>("sp_GetActiveProductList", mergeOption);
        }
    
        public virtual ObjectResult<ProductRecord> sp_GetNewProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductRecord>("sp_GetNewProducts");
        }
    
        public virtual ObjectResult<ProductRecord> sp_GetNewProducts(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductRecord>("sp_GetNewProducts", mergeOption);
        }
    
        public virtual ObjectResult<ProductRecord> sp_GetProductBySearch(string product_SKU, string mAP_Price)
        {
            var product_SKUParameter = product_SKU != null ?
                new ObjectParameter("Product_SKU", product_SKU) :
                new ObjectParameter("Product_SKU", typeof(string));
    
            var mAP_PriceParameter = mAP_Price != null ?
                new ObjectParameter("MAP_Price", mAP_Price) :
                new ObjectParameter("MAP_Price", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductRecord>("sp_GetProductBySearch", product_SKUParameter, mAP_PriceParameter);
        }
    
        public virtual ObjectResult<ProductRecord> sp_GetProductBySearch(string product_SKU, string mAP_Price, MergeOption mergeOption)
        {
            var product_SKUParameter = product_SKU != null ?
                new ObjectParameter("Product_SKU", product_SKU) :
                new ObjectParameter("Product_SKU", typeof(string));
    
            var mAP_PriceParameter = mAP_Price != null ?
                new ObjectParameter("MAP_Price", mAP_Price) :
                new ObjectParameter("MAP_Price", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductRecord>("sp_GetProductBySearch", mergeOption, product_SKUParameter, mAP_PriceParameter);
        }
    }
}
